apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bchkh/gitops-project.git  #  Git repo
    targetRevision: main
    path: apps/redis  # Path to  redis manifests
  destination:
    server: https://kubernetes.default.svc  # Minikube cluster
    namespace: default
  syncPolicy:
    automated: {}  # Auto-sync on Git changes